import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — The Wise Room',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-vellum">
      <div className="max-w-[680px] mx-auto px-7 py-12">
        <Link
          href="/"
          className="font-cormorant text-[20px] font-medium text-ink hover:underline underline-offset-2 decoration-[0.5px]"
        >
          Great Minds
        </Link>

        <article className="mt-10 space-y-7">
          <header className="space-y-2">
            <h1 className="font-cormorant text-[32px] font-medium text-ink leading-tight">
              Terms of Service
            </h1>
            <p className="font-lora text-[12px] text-sepia">
              Effective: 19 May 2026 · Version 1.1
            </p>
          </header>

          <Section title="1. Welcome">
            These Terms govern your use of Great Minds (the &ldquo;Service&rdquo;), an AI-powered reflective companion that lets you have written conversations with personas inspired by historical thinkers. By using the Service, you agree to these Terms. If you do not agree, do not use the Service.
          </Section>

          <Section title="2. Who We Are">
            Great Minds is operated from Greece. You can reach us at <Email />.
          </Section>

          <Section title="3. The Service">
            Great Minds provides written, conversational interactions with AI-generated personas inspired by historical figures. The personas are fictional reconstructions, not actual representations of historical individuals or their views.
            {' '}
            The Service is provided <strong className="font-lora font-medium text-ink">for personal reflection only</strong>. It is not, and is not a substitute for: therapy, counseling, or psychological treatment; medical advice, diagnosis, or treatment; crisis support or emergency services; legal, financial, or professional advice of any kind.
            {' '}
            If you are in crisis or in immediate danger, contact local emergency services or a qualified professional.
          </Section>

          <Section title="4. Eligibility">
            You must be at least 18 years old to use the Service. By creating an account, you confirm you meet this requirement.
          </Section>

          <Section title="5. Account">
            You authenticate with your email address using one-time codes (&ldquo;OTP&rdquo;). You are responsible for keeping your email account secure. You may not share your account.
          </Section>

          <Section title="6. Your Content">
            When you have a conversation with a persona, the messages you write are stored to provide the Service (including continuity across sessions). See our <Link href="/legal/privacy" className="text-ink underline underline-offset-2 decoration-[0.5px]">Privacy Policy</Link> for how we handle your data. You retain ownership of what you write. You grant us a limited license to process, store, and transmit your messages solely to operate the Service.
          </Section>

          <Section title="7. AI-Generated Content">
            Persona responses are generated by large language models. They may be inaccurate, incomplete, or inconsistent; should not be treated as authoritative or factual; do not represent the views of the historical figures referenced; and do not constitute professional advice of any kind. We do not guarantee any specific outcome from using the Service.
          </Section>

          <Section title="8. Acceptable Use">
            You agree not to: use the Service for unlawful purposes; attempt to bypass authentication, rate limits, or other technical controls; reverse engineer, scrape, or systematically extract content; submit content that is illegal, harmful, or violates the rights of others; or use the Service to generate content that could harm yourself or others. We may suspend or terminate your account if you violate these terms.
          </Section>

          <Section title="9. Subscriptions and Payment">
            The Service is offered as a free tier and a Pro subscription tier. Pro subscriptions are processed by Stripe and billed monthly at €14.90/month or annually at €149/year. You can cancel your subscription at any time via your Account screen, which opens the Stripe customer portal. Cancellation takes effect at the end of your current billing period.
          </Section>

          <Section title="10. Intellectual Property">
            The Service, including its design, content, and software, is owned by Great Minds. The historical figures referenced are public-domain personas; the persona configurations are our own work.
          </Section>

          <Section title="11. Termination">
            You may stop using the Service and request account deletion at any time. We may suspend or terminate accounts that violate these Terms, with or without notice.
          </Section>

          <Section title="12. Disclaimers">
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI RESPONSES WILL BE ACCURATE OR FIT FOR ANY PURPOSE. To the maximum extent permitted by applicable law, we disclaim all warranties, express or implied.
          </Section>

          <Section title="13. Limitation of Liability">
            To the maximum extent permitted by applicable law, our total liability for any claim arising from your use of the Service is limited to the amounts you have paid us in the 12 months preceding the claim, or €50, whichever is greater. We are not liable for indirect, incidental, consequential, or punitive damages. These limits do not affect rights you have under mandatory consumer protection laws.
          </Section>

          <Section title="14. Governing Law">
            These Terms are governed by the laws of Greece. Disputes will be resolved in the competent courts of Athens, Greece, without prejudice to mandatory consumer rights to bring claims in your country of residence.
          </Section>

          <Section title="15. Changes">
            We may update these Terms. Material changes will be communicated via the Service. Continued use after changes take effect constitutes acceptance.
          </Section>

          <Section title="16. Contact">
            Questions about these Terms: <Email />.
          </Section>
        </article>
      </div>
    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-cormorant text-[22px] font-medium text-ink leading-tight">
        {title}
      </h2>
      <p className="font-lora text-[14px] text-charcoal leading-[1.7]">
        {children}
      </p>
    </section>
  )
}

function Email() {
  return (
    <a
      href="mailto:support@thegreatminds.app"
      className="text-ink underline underline-offset-2 decoration-[0.5px]"
    >
      support@thegreatminds.app
    </a>
  )
}
